apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantum-resilient-orchestrator.fullname" . }}
  labels:
    {{- include "quantum-resilient-orchestrator.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "quantum-resilient-orchestrator.selectorLabels" . | nindent 4 }}

