{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quantum-resilient.serviceAccountName" . }}
  labels:
    {{- include "quantum-resilient.labels" . | nindent 4 }}
    component: rbac
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

