from __future__ import annotations

import time
from pathlib import Path
from typing import List

from .config_loader import ExperimentConfig, load_experiment_config
from .adapters import load_rust_adapters, select_adapters, CryptoAdapter
from .env_snapshot import write_snapshot_json
from .metrics import aggregate_jsonl_to_csv, write_raw_events_csv
from .reporting import run_analysis_and_report
from .schema_validate import validate_metrics_jsonl


def run_experiment(config_path: str) -> None:
	cfg: ExperimentConfig = load_experiment_config(config_path)

	out_dir = Path(cfg.output.get("directory", "./results"))
	out_dir.mkdir(parents=True, exist_ok=True)

	# Environment snapshot
	write_snapshot_json(str(out_dir / "environment.json"))

	# Load all Rust adapters via PyO3 (if available) and select by name
	all_adapters = load_rust_adapters()
	requested = []
	requested.extend(cfg.algorithms.get("pqc", []))
	requested.extend(cfg.algorithms.get("symmetric", []))
	requested.extend(cfg.algorithms.get("classical", {}).get("key_exchange", []))
	requested.extend(cfg.algorithms.get("classical", {}).get("signature", []))
	adapters: List[CryptoAdapter] = select_adapters(all_adapters, requested)

	# Warmup
	if cfg.warmup_seconds > 0:
		_deadline = time.time() + cfg.warmup_seconds
		while time.time() < _deadline:
			time.sleep(0.01)

	# Run repetitions (delegation to Rust is expected; placeholder pacing here)
	for _ in range(cfg.repetitions):
		time.sleep(0.01)
	# Minimal PyO3 execution (if adapters available)
	if adapters:
		adapter = adapters[0]
		try:
			pk, sk = adapter.keygen()  # type: ignore[attr-defined]
			_ = adapter.name()         # type: ignore[attr-defined]
			# If encapsulate exists, exercise it
			try:
				_ = adapter.encapsulate(pk)  # type: ignore[attr-defined]
			except Exception:
				pass
		except Exception:
			# Non-fatal; continue to reporting
			pass

	# Aggregate metrics JSONL (if generated by Rust core) to CSV
	jsonl_path = str(out_dir / "metrics.jsonl")
	csv_path = str(out_dir / "metrics.csv")
	aggregate_jsonl_to_csv(jsonl_path, csv_path)
	# Raw events CSV (schema-aligned)
	write_raw_events_csv(str(out_dir))
	# Analytics and report
	run_analysis_and_report(str(out_dir))
	# Metrics schema validation
	schema_path = Path("configs/metrics_schema.yaml")
	if schema_path.exists():
		report = validate_metrics_jsonl(jsonl_path, str(schema_path))
		(out_dir / "metrics_validation.json").write_text(__import__("json").dumps(report, indent=2), encoding="utf-8")


