replicaCount: 1

rustCoreImage:
  repository: pqc-benchmarking-skeleton
  tag: latest
  pullPolicy: IfNotPresent
  metricsPort: 9100

orchestratorImage:
  repository: pqc-benchmarking-skeleton
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

prometheus:
  scrape: true

results:
  bucket: ""   # set to GCS bucket name or leave empty for local PVC

orchestrator:
  configMapName: "experiment-config"
  configFileName: "experiment.yaml"
  outputDir: "/results"
  serviceAccountName: ""   # set to SA bound to GCS writer if using GCS


